version: '2'

### Spring profile flags are not recommended
### According to the 12 factor app standard, env variables should be defined on the machine not in a project file

### TODO - Hide ports with env variables??? seems excessive


services:
  app:
    image: 'bradleypelton/starfirst:latest'
    build:
      context: .
    ports:
      - "80:8080"
#      - "443:8080"
    container_name: app
    depends_on:
      - db
      - elasticsearch
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${starDecPostgresMainDbName}
      - SPRING_DATASOURCE_USERNAME=${starDecPostgresUsername}
      - SPRING_DATASOURCE_PASSWORD=${starDecPostgresPassword}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      #- starDecElasticUrl=elasticsearch:9200
      - starDecJwtSecretKey=${starDecJwtSecretKey}
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/starpostgresdb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=password
##      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
##      - starDecElasticUrl=localhost:9200
#      - starDecElasticUrl=elasticsearch:9200
#      - starDecJwtSecretKey=FAKEKEY
    networks:
      - starnet
  db:
    image: 'postgres:13'
#    volumes:
#      - postgres_data:/var/lib/postgresl/data/
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${starDecPostgresMainDbName}
      - POSTGRES_USER=${starDecPostgresUsername}
      - POSTGRES_PASSWORD=${starDecPostgresPassword}
    networks:
      - starnet
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      #      - discovery.seed_hosts=elasticsearch
      #      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
#    volumes:
#      - esdata1:/usr/share/elasticsearch/data
    ports:
#      - "9300:9300"
      - "9200:9200"
    networks:
      - starnet
networks:
  starnet: